###
GET http://localhost:5000/barang

###
DELETE http://localhost:5000/barang/delete/17

###
POST http://localhost:5000/barang/create
Content-Type: application/json

{
    "nama_barang": "Nintendo DS",
    "harga": 350000
}

###
PATCH http://localhost:5000/barang/edit/4
Content-Type: application/json

{
    "nama_barang": "Ikan Lele",
    "harga": 1500
}

###
DELETE http://localhost:5000/barang/delete/34